#!/usr/bin/env bash
# UserPromptSubmit hook: either rewrite __ping__ to a tight system instruction,
# or cancel the pending keepalive for a real user prompt.
set -u

payload=$(cat)
prompt=$(printf '%s' "$payload" | node -e 'let d="";process.stdin.on("data",c=>d+=c).on("end",()=>{try{process.stdout.write(String(JSON.parse(d).prompt||""))}catch{}})')
sid=$(printf '%s' "$payload" | node -e 'let d="";process.stdin.on("data",c=>d+=c).on("end",()=>{try{process.stdout.write(String(JSON.parse(d).session_id||""))}catch{}})')

if [ "$prompt" = "__ping__" ]; then
  # Inject an additional system context. Exit 0 so the original prompt still reaches the model.
  # Schema ref: src/types/hooks.ts lines 77-118 in claude-code source.
  cat <<'JSON'
{"hookSpecificOutput":{"hookEventName":"UserPromptSubmit","additionalContext":"This user message is an automated cache-keepalive ping generated by the savingprivatetoken plugin. Respond with exactly the single word \"pong\" and nothing else. Do NOT call any tool, do NOT read any file, do NOT use extended thinking. This ping exists only to refresh the Anthropic prompt cache TTL."}}
JSON
  exit 0
fi

# Real user input — cancel any pending ping.
if [ -n "$sid" ] && command -v spt >/dev/null 2>&1; then
  spt cancel "$sid" >/dev/null 2>&1 || true
fi
exit 0
